[info]
description = "Ge'ez Config File"
version = "2023-10-02"

[data]
geez = { path = "./code.toml" }
punctuation = { path = "./punctuation.toml" }

[translators]
numerals = "scripts/numerals.rhai"
