[info]
name = "Amharic IM"
description = "Amharic Config File"
version = "2026-07-24"
authors = []
website = ""

[core]
buffer_size = 64
auto_capitalize = false
auto_commit = true

[data]
geez_punctuation = { path = "../gez/punctuation.toml" }
amharic = { path = "./code.toml" }

[translation]
dictionary = { path = "./dictionary.toml" }
names = { path = "./names.toml" }

[translators]
date = "./scripts/datetime/date.rhai"
geez_numerals = "../gez/scripts/numerals.rhai"
