[info]
description = "Amharic Config File"
version = "2023-10-02"

[data]
geez = { path = "../gez/code.toml" }
geez_punctuation = { path = "../gez/punctuation.toml" }
# The amharic code will overwrite the geez code
amharic = { path = "./code.toml" }

[translation]
dictionary = { path = "./dictionary.toml" }
names = { path = "./names.toml" }

[translators]
date = "./scripts/datetime/date.rhai"
geez_numerals = "../gez/scripts/numerals.rhai"
