[info]
name = "Amharic IM"
description = "Amharic Config File"
version = "2024-03-23"
authors = []
website = ""

[core]
buffer_size = 64
auto_capitalize = false
auto_commit = true

[data]
geez = { path = "../gez/code.toml" }
geez_punctuation = { path = "../gez/punctuation.toml" }
# The amharic code will overwrite the geez code
amharic = { path = "./code.toml" }

[translation]
names = { path = "./names.toml" }

[translators]
date = "./scripts/datetime/date.rhai"
geez_numerals = "../gez/scripts/numerals.rhai"
