[info]
description = "Amharic Clafrica Config File"
version = "2023-10-02"

[data]
geez = { path = "../geez/code.toml" }
geez_punctuation = { path = "../geez/punctuation.toml" }
# The amharic code will overwrite the geez code
amharic = { path = "./code.toml" }

[translation]
dictionary = { path = "./dictionary.toml" }
names = { path = "./names.toml" }

[translator]
date = "./scripts/datetime/date.rhai"
geez_numerals = "../geez/scripts/numerals.rhai"
