[info]
source = "https://github.com/germes96/ETTA/blob/main/datas/words.csv"
description = "Ewondo words"
version = "2023-06-21"

[translation]
"a" = "a"
"a1mo1s" = "àmòs"
"a2" = "á"
"a2be2" = "ábé"
"a2bum" = "ábum"
"a2so7n*" = "ásǒŋ"
"a2wa2la2" = "áwálá"
"a2wola" = "áwola"
"a2ye2" = "áyé"
"abo*7g" = "abɔ̌g"
"abui" = "abui"
"abum" = "abum"
# TODO: fix the problem with the clafrica code
#       is the word correct?
# "afe2" = "afé"
"aheu2b" = "ahə́b"
"ai" = "ε"
"akali" = "akali"
"aki" = "aki"
"aku2da" = "akúda"
"alodogo" = "alodogo"
"awo5m" = "awôm"
"awola" = "awola"
"ba2la2" = "bálá"
"ba2li" = "báli"
"bai" = "bε"
"bai2" = "bέ"
"bai7" = "bɛ̌"
"beu" = "bə"
"beu2b" = "bə́b"
"beu2bai2" = "bə́bέ"
"beu2lai2" = "bə́lέ"
"beu2leu2" = "bə́lə́"
"beu2nyi1" = "bə́nyì"
"beu2saman" = "bə́saman"
"beu2ta2n" = "bə́tán"
"beuleu2" = "bələ́"
"bi" = "bi"
"bi1zeuzeug" = "bìzəzəg"
"bi2" = "bí"
"bi2a" = "bía"
"bi2ta2n" = "bítán"
"bi7" = "bǐ"
"bi5" = "bî"
"bidzu7ga2" = "bidzǔgá"
"bieu2m" = "biə́m"
"biko*n" = "bikɔn"
"binyutain" = "binyutεn"
"bizeuzeug" = "bizəzəg"
"bo*" = "bɔ"
"da2" = "dá"
"dan*" = "daŋ"
"deu2" = "də́"
"di2" = "dí"
"di2a" = "día"
"di2g" = "díg"
"di2li2" = "dílí"
"din*" = "diŋ"
"dza7l" = "dzǎl"
"dza7m" = "dzǎm"
"dza7ma" = "dzǎma"
"dza7ma2" = "dzǎmá"
"dzaa" = "dzaa"
"dzameu" = "dzamə"
"dze2" = "dzé"
"dzi2li2" = "dzílí"
"dzia2" = "dzíá"
"dzo2m" = "dzóm"
"dzoe2" = "dzoé"
"e" = "e"
"e2" = "é"
"e2bul" = "ébul"
"e2tun" = "étun"
"ebu2l" = "ebúl"
"ebul" = "ebul"
"ebulu5" = "ebulû"
"etie2" = "etíé"
"etsamakag" = "etsamakag"
"etun" = "etun"
"ewondo" = "ewondo"
"feu" = "fə"
"fi2ba" = "fíba"
"fie" = "fie"
"fo2da" = "fóda"
"fulade2" = "fuladé"
"fwa2" = "fwá"
"ga2to2" = "gátó"
"ha" = "ha"
"ha2neu" = "hánə"
"heu2" = "hə́"
"ho*2g" = "hɔ́g"
"iko*2da" = "ikɔ́da"
"kadeu" = "kadə"
"keu" = "kə"
"keu2" = "kə́"
"keuleu2" = "kələ́"
"ki2di2" = "kídí"
"ki2g" = "kíg"
"ki2n*" = "kíŋ"
"kie2" = "kíé"
"kig" = "kig"
"ko*2b" = "kɔ́b"
"ko*7s" = "kɔ̌s"
"ko*n" = "kɔn"
"ko2n" = "kón"
"kofi2" = "kofí"
"ku2b" = "kúb"
"kudukudu" = "kudukudu"
"kus" = "kus"
"la2la" = "lála"
"lai2" = "lέ"
"leu2b" = "lə́b"
"m1beumbeu" = "m̀bəmbə"
"m1bo*2g" = "m̀bɔ́g"
"m1bo2" = "m̀bó"
"ma" = "ma"
"ma2" = "má"
"ma7" = "mǎ"
"maba2nda" = "mabánda"
"madin*" = "madiŋ"
"maso*2" = "masɔ́"
"masug" = "masug"
"mayi" = "mayi"
"mazu" = "mazu"
"mba2n*eula" = "mbáŋəla"
"mbeumbeu" = "mbəmbə"
"mbo*2" = "mbɔ́"
"mbon*" = "mboŋ"
"me2ki2d" = "mékíd"
"meu" = "mə"
"meu2" = "mə́"
"meu2lai2" = "mə́lέ"
"meu2nyi" = "mə́nyi"
"meu2nyina" = "mə́nyina"
"meu2saman" = "mə́saman"
"meu2ta2n" = "mə́tán"
"meu2to2a" = "mə́tóa"
"meulu2" = "məlú"
"meundi2m" = "məndím"
"meuto2da" = "mətóda"
"meuwo2m" = "məwóm"
"meuwola" = "məwola"
"mi" = "mi"
"mi2a" = "mía"
"mi2bai2" = "míbέ"
"mi2nta2n*ai2n" = "míntáŋέn"
"mi2ntie" = "míntie"
"min1son" = "miǹson"
"mina2" = "miná"
"mintag" = "mintag"
"mintaid" = "mintεd"
"mintie" = "mintie"
"mkpa2mai2n" = "mkpámέn"
"mo*2ndi" = "mɔ́ndi"
"mod" = "mod"
"mu2na2" = "múná"
"mveun*" = "mvəŋ"
"mwom" = "mwom"
"mwomo" = "mwomo"
"n*1ga2l" = "ŋ̀gál"
"n*1go2la" = "ŋ̀góla"
"n*2go2la" = "ŋ́góla"
"n*ga7n*" = "ŋgǎŋ"
"n*go*n" = "ŋgɔn"
"n*goe" = "ŋgoe"
"n*ko*geulai2n" = "ŋkɔgəlέn"
"n1dzwa2n*" = "ǹdzwáŋ"
"n1lo2" = "ǹló"
"n1nam" = "ǹnam"
"n1neu2m" = "ǹnə́m"
"n1no2m" = "ǹnóm"
"n1taid" = "ǹtεd"
"n1tuba" = "ǹtuba"
"n1yeu2geuleu" = "ǹyə́gələ"
"na2la2" = "nálá"
"na5" = "nâ"
"ndeu2" = "ndə́"
"ndo*" = "ndɔ"
"ndu2gudu" = "ndúgudu"
"ndza2mai2n" = "ndzámέn"
"neu" = "nə"
"neu2" = "nə́"
"nga7" = "ngǎ"
"no*1n*" = "nɔ̀ŋ"
"no*2n*" = "nɔ́ŋ"
"nyag" = "nyag"
"nyi" = "nyi"
"nyie" = "nyie"
"nyina" = "nyina"
"nyo*2" = "nyɔ́"
"o" = "o"
"o2" = "ó"
"o2de2n" = "ódén"
"o2ki2di2" = "ókídí"
"oki2di2" = "okídí"
"oko*n" = "okɔn"
"opeub" = "opəb"
"osu2" = "osú"
"owondo" = "owondo"
"paulus" = "paulus"
"sa1ma1n" = "sàmàn"
"saman" = "saman"
"seu2seure2" = "sə́səré"
"so*2ndo*" = "sɔ́ndɔ"
"su2lugu" = "súlugu"
"ta2n" = "tán"
"ta2n*" = "táŋ"
"ta2n*eu2ya2" = "táŋə́yá"
"ta2na" = "tána"
"taigai" = "tεgε"
"te2" = "té"
"teu2m" = "tə́m"
"teu2teuleu" = "tə́tələ"
"ti2kai2d" = "tíkέd"
"to*2sin" = "tɔ́sin"
"to*7" = "tɔ̌"
"tse2nde" = "tsénde"
"tsi2d" = "tsíd"
"tsi2dko*7s" = "tsídkɔ̌s"
"ve2" = "vé"
"via2n" = "víán"
"vo*2li" = "vɔ́li"
"wa" = "wa"
"wa1" = "wà"
"wa2" = "wá"
"wa5n" = "wân"
"wo2deuneu" = "wódənə"
"ya" = "ya"
"ya2" = "yá"
"ya2m" = "yám"
"ye5neu" = "yênə"
"yeu1meu1neu1" = "yə̀mə̀nə̀"
"yi" = "yi"
"za2n*" = "záŋ"
"zamgba2l" = "zamgbál"
"zamgba2la" = "zamgbála"
"ze7n" = "zěn"
"zeu2" = "zə́"
"zeuzeu" = "zəzə"
