[info]
name		=	"nufi"
description = 	"Nufi Config File"
authors		=	["Resulam <contact@resulam.com>"]
website		=	"https://resulam.com"
version		=	"2024-03-23"

[core]
buffer_size = 64
auto_capitalize = true
auto_commit = true

[translation]
sms = { path = "./nufi_sms.toml" }

[translators]
date = "./scripts/datetime/date.rhai"
numerals = "./scripts/numerals.rhai"

[data]
clafrica = { path = "../clafrica/clafrica.toml" }
