[info]
name		=	"nufi_sms_raccourci"
description = 	"Nufi SMS Raccourci Shortcuts"
authors		=	["Resulam <contact@resulam.com>"]
website		=	"https://resulam.com"
version		=	"2023-07-06"

[translation]
"+a" = "shwì' ā"
"aghmh?" = "ǎ ghèn mɑ̀ hɑ̄ ?"
"almk?" = "ǎ lén mɑ́ kɑ́ ?"
"almkl?" = "ǎ lén mɑ́ kɑ́ lī?"
"am2" = "ǎ mɑ́"
"amh?" = "ǎ mɑ̀ hɑ̄ ?"
"amnd" = "ǎ mɑ̀ndīē"
"amngk?" = "ǎ mɑ̀ngʉ́ kɑ́ ?"
"amni" = "ǎ mɑ̀nní"
"amnsii" = "ǎ mɑ̀nsíí"
"amw?" = "ǎ mɑ́ wɑ̄ ?"
"andk" = "A ndʉ̂ kə"
"ansmh?" = "ǎ nsī mɑ̀ hɑ̄ ?"
"assb" = "à sī sīē bɑ̄"
"c'sl'z" = "cà'sǐ líé'zī"
"cc'" = "cīcō'ò"
"cklkk" = "cák lò kīkēē"
"cmna" = "Ca᷅mnà'"
"cng'k'" = "cēh ngà'kà'"
"cngaka'" = "cēh ngà'kà'"
"cngw" = "cə̄ə̄ ngwāh"
"cpnwala'" = "cēh pɑ̀ŋwâtlɑ̄'"
"csl'z" = "cômsǐlíé'zī"
"cslz" = "cômsǐlíé'zī"
"cw'hw" = "cwě' hwíé"
"cw'mk" = "cwè' mɑ́ kɑ́ ?"
"cwn$" = "cwǎnù"
"cwnb" = "cwǎnù bɑ́"
"dpp" = "dīē pə̀pē'"
"f'b" = "fà'á bɑ́"
"f'pp'" = "fɑ̌' pə̀pē'"
"fb" = "fà'á bɑ́"
"fhmnko" = "fóh mɑ̀nkō"
"fhn" = "fōhnì"
"fhsnd" = "fhʉ̄ sáá ndó"
"fhz" = "fɑ̌hnzɑ̄"
"fpp" = "fɑ̌' pə̀pē'"
"ghmw" = "ghʉ̀ mɑ̀wǎ"
"ghnd'nd'" = "ghʉ̌ ndɑ̀'ndɑ̀'"
"ghszh" = "ghʉ̀ sì zhī"
"ghl'" = "ghə̀ə̄lɑ̄'"
"yckm" = "yáá ncāk mɑ́"
"hmbipa" = "hɑ̄ mbí pɑ̀h"
"hmbipo" = "hɑ̄ mbí pō"
"hmbua" = "hɑ̄ mbú à"
"hmbui" = "hɑ̄ mbú ì"
"hpi" = "Hɑ̄āpìì"
"hszh" = "hèè sì zhī"
"hwsnao" = "hwīēsī nā ò"
"kb?" = "kɑ́ bɑ́ ɑ̄ ?"
"kbyb?" = "kɑ́ bɑ́ yì béè ?"
"kcnt" = "kə̀cɔ̀ nə̀tǐ' !"
"ks" = "wèn kōsī ā lɑ́ ō ō ō !"
"ktmng?" = "kɑ́ tɑ́ ó mɑ̀ngʉ́ ʉ̄ ?"
"ktmngf?" = "kɑ́ tɑ́ ó mɑ̀ngʉ́ fà'á ā ?"
"l mb mf ng mbh" = "lǎh mbè' mfɑ̀' ngén mbhì"
"l nsh o" = "lā' nshù ō"
"l s" = "lǒ sáá"
"l'nsho" = "lā' nshù ō"
"l'ys" = "lā' ywààsì !"
"lhsa" = "lɑ̀hsì ā lɑ́"
"lhza" = "lóh zɑ́h à"
"lmb'mf'ngmbh" = "lǎh mbè' mfɑ̀' ngén mbhì"
"lmbipa" = "lēn mbí pɑ̀h"
"lmbipo" = "lēn mbí pō"
"lmbmfngmbh" = "lǎh mbè' mfɑ̀' ngén mbhì"
"lmbua" = "lēn mbú à"
"lmbui$" = "lēn mbú ì"
"lmbuim" = "lēn mbú í mɑ́"
"lmng'" = "lēn mɑ́ ngǎ'"
"lmnga" = "lēn mɑ́ ngǎ'"
"lmnh" = "lēn mɑ́ ŋ̄h"
"ln$" = "lʉ̀ʉ̄ nā ò !"
"lnsbw" = "lɛ̂n su bə ɑ̂ wə?"
"lnthngc" = "lǎh nthʉ̄ ō ngén càm"
"lys" = "lā' ywààsì !"
"m mb" = "mɑ́ mbɑ̀ !"
"mb'$" = "mbè'"
"mb'mb'" = "mbè'mbè'"
"mb'mb'fz" = "mbè'mbè' fɑ̌hnzɑ̄"
"mb'mb'lz" = "mbè'mbè' líé'zī"
"mb'mb'mbz" = "mbè'mbè' mbūànzɑ̄"
"mb'mf'" = "mbè' mfɑ̀'"
"mb'ntma" = "mbǎ'ntām à"
"mb'o" = "mbɑ̄' ō"
"mb'tm" = "mbī'tū mɑ́"
"mbf$" = "mbè' mfɑ̀'"
"mbf'" = "mbɑ̀ fà'á"
"mbk$" = "mbàk"
"mbkmnd" = "mbǎk mɑ̀ndō"
"mbkngf" = "mbàkngòfāt"
"mbksmndb" = "mbàk sī mɑ̀ndō bɑ̄"
"mbl" = "mbə̄ə̄ lɑ́"
"mbmb" = "mbə̄ə̄ mbɑ̀"
"mbmngcso" = "mbɑ̀ mʉ̀ ngɑ̌ cɑ̀'sì ō lɑ́"
"mbmngkw'o" = "mbɑ̀ mʉ̀ ngɑ̌ kwè' ō"
"mbmngpno" = "mbɑ̀ mʉ̀ ngɑ̌ pén ō"
"mbmpn" = "mbɑ̀ mʉ̌ pén ō"
"mbnibmw" = "Mbūànì bɑ̄ mɑ̀ wò "
"mbntma" = "mbǎ'ntām à"
"mbpen" = "mbí pèn"
"mbz$" = "mbūànzɑ̄"
"mbzh" = "Mbóó zhī"
"mf'skw'nkw'" = "mfɑ̀' sìkwè'nkwé'"
"mfskwnkw" = "mfɑ̀' sìkwè'nkwé'"
"mgw" = "Mòōngwê"
"mkghl?" = "mɑ́ kɑ́ ghʉ̀ lī ?"
"mkl?" = "mɑ́ kɑ́ lī ?"
"mkln?" = "mɑ́ kɑ́ lī nɑ̀ ?"
"mlbt$" = "Mə lɑ̀btə̀"
"mlbto" = "Mə lɑ̀btə̀ ō"
"mm0" = "mēmmɑ̄ ò"
"mmsh" = "mòmòshʉ̄"
"mndka" = "mʉ̀ ndǒk à"
"mnia'ya" = "mēnìá' yāā"
"mseu" = "mēnsə̀ə̀"
"mvo" = "mɑ̄vǒ"
"mwuya" = "mēn-wú yāā"
"mz" = "mɑ̀nzɑ̄"
"n gh a" = "nǔ ghʉ̀ ā"
"n k c" = "ǹ kɑ̀' cə̄ə̄"
"n k zh" = "ǹ kɑ̀' zhī"
"n t" = "nù tɑ̀' !"
"n'sie" = "ně' sīē"
"nc s w b" = "ncà' sī wū bɑ̄"
"nc'lb" = "ncǎ' lɑ̀ bɑ̄"
"nc'swb" = "ncà' sī wū bɑ̄"
"nclb" = "ncǎ' lɑ̀ bɑ̄"
"ncswb" = "ncà' sī wū bɑ̄"
"ncw'" = "ngɑ̌ kúɑ́ ncwē'! ncwé' tāt lá ndʉ̄ɑ̄ !"
"nd'f" = "ndʉ̂'fōh"
"nd'm" = "ndɑ̌'mɑ́"
"nd'nd'$" = "ndɑ̀'ndɑ̀'"
"nd'nd'bn" = "ndɑ̀'ndɑ̀' bɑ̌ nù"
"nd'nd'mn" = "ndɑ̀'ndɑ̀' mɑ̌ nù"
"nd'nsh" = "ndʉ̂'nshì"
"ndgw" = "Ndə̀ə̄ngwê"
"ndka$" = "ndǒk à"
"ndkam" = "Ndə̀ə̄nkām"
"ndki" = "ndǒk ì"
"ndko" = "ndǒk ò"
"ndnd b" = "ndéndēē bɑ́"
"ndnd$" = "ndéndēē"
"ndndb" = "ndéndēē bɑ́"
"ndsc'lp" = "ndʉ̄ɑ̄ sì cɑ̀'sì lɑ̀pìé"
"ndsc'mn" = "ndòm sīècɑ̄' mɑ́ nēhē"
"ndsclp" = "ndʉ̄ɑ̄ sì cɑ̀'sì lɑ̀pìé"
"ndscmn" = "ndòm sīècɑ̄' mɑ́ nēhē"
"ng k zhw" = "ngɑ̌ kúɑ́ zhwìè"
"ng ns m" = "ngɑ̌ nsī mɑ̀"
"ng ns p" = "ngɑ̌ nsī pí"
"ng nt" = "ngɑ̌ ntèn"
"ng p n" = "ngɑ̌ pén ō"
"ng t ng t o" = "ngɑ̌ tám ngáá tú ò"
"ng y'" = "ngɑ̌ yú'"
"ng zh" = "ngɑ̌ zhí"
"ng'." = "ngǎ'"
"ng'fi" = "ngù'fī"
"ng'k'" = "ngà'kà'"
"ng'ko" = "Ngǎ'kò"
"ng'naa$" = "ngǎ' nā à !"
"ng'naap" = "ngǎ' nā à pʉ̀mbè !"
"ng'w'n" = "ngà' ŋwɑ̀'nì"
"ng7" = "ngɑ̌"
"ngc's$" = "ngɑ̌ cɑ̀'sì"
"ngc'sol" = "ngɑ̌ cɑ̀'sì ō lɑ́"
"ngc'sylpm" = "ngɑ̌ cɑ̀'sì yēē lɑ́ póómɑ̄"
"ngcahs" = "ngɑ̌ cáhsí"
"ngcmf" = "ngɑ̌ cóh mfɑ̀'"
"ngcoh$" = "ngɑ̌ cóh"
"ngcohmf" = "ngɑ̌ cóh mfɑ̀'"
"ngcs$" = "ngɑ̌ cáhsí"
"ngcsol" = "ngɑ̌ cɑ̀'sì ō lɑ́"
"ngdmbnt" = "ǒ díé mbɑ̄ lāhā ?"
"ngfhmnd" = "ngɑ̌ fhʉ́mɑ̄ndīē"
"ngfhmnsn" = "ngɑ̌ fhʉ́mɑ̄nsóh nā à"
"nggh" = "ngɑ̌ ghʉ̌"
"ngha" = "nǔ ghʉ̀ ā"
"nght" = "ngɑ̌ hèè tɑ̀'"
"ngko" = "Ngǎ'kò"
"ngkw'$" = "ngɑ̌ kwà'"
"ngkw'f'" = "ngɑ̌ kwà' fà'á"
"ngkw'o" = "ngɑ̌ kwè' ō"
"ngkwf" = "ngɑ̌ kwà' fà'á"
"ngkwo" = "ngɑ̌ kwè' ō"
"ngkzhw" = "ngɑ̌ kúɑ́ zhwìè"
"nglmng'" = "ngɑ̌ lén mɑ́ ngǎ'"
"nglmnga" = "ngɑ̌ lén mɑ́ ngǎ'"
"nglsio" = "ngɑ̌ lɑ̀ɑ̀sì ō"
"nglso" = "ngɑ̌ lɑ̀ɑ̀sì ō"
"ngm." = "ngɑ̌ mɑ̀"
"ngm1" = "ngɑ̌ mɑ̀"
"ngm2" = "ngɑ̌ mɑ́"
"ngmh" = "ngɑ̌ mèh"
"ngmmf" = "ngɑ̌ mɑ̀ mfɑ́'"
"ngmncwnt" = "ngɑ̌ mɑ̀ncwáántīē"
"ngmnd" = "ngɑ̌ mɑ̀ndīē"
"ngmnees" = "ngɑ̌ mɑ̀nnēēsī"
"ngmng$" = "ngɑ̌ mɑ̀ngóó"
"ngmngoo" = "ngɑ̌ mɑ̀ngóó"
"ngmni" = "ngɑ̌ mɑ̀nní"
"ngmns$" = "ngɑ̌ mɑ̀nnēēsī"
"ngmnsii" = "ngɑ̌ mɑ̀nsíí"
"ngmnsohna" = "ngɑ̌ mɑ̀nsóh nā à"
"ngmnsoko" = "ngɑ̌ mɑ̀nsōk ō"
"ngmnzwz" = "ngɑ̌ mɑ̀nzɑ̄ wúzɑ̄"
"ngmzwz" = "ngɑ̌ mɑ̀nzɑ̄ wúzɑ̄"
"ngngd" = "ngɑ̌ ngén dīē"
"ngngmmf" = "ngɑ̌ ngén mɑ̀ mfɑ̀'"
"ngngzwz" = "ngɑ̌ ngén zɑ̄ wúzɑ̄"
"ngnsm" = "ngɑ̌ nsī mɑ̀"
"ngnsndka" = "ngɑ̌ nsī ndǒk à"
"ngnsp" = "ngɑ̌ nsī pí"
"ngnt" = "ngɑ̌ ntèn"
"ngnwn" = "ngà' ŋwɑ̀'nì"
"ngpn." = "ngɑ̌ pén ō"
"ngpno" = "ngɑ̌ pén ō"
"ngpt" = "ngɑ̌ pén tɑ̀'"
"ngpua" = "ngɑ̌ púá"
"ngpy" = "ngɑ̌ pén yēē"
"ngtmngto" = "ngɑ̌ tám ngáá tú ò"
"ngtngto" = "ngɑ̌ tám ngáá tú ò"
"ngy'$" = "ngɑ̌ yú'"
"ngy'nthmbo" = "ngɑ̌ yá'nthʉ́ mbú ò"
"ngya'nthmbo" = "ngɑ̌ yá'nthʉ́ mbú ò"
"ngynthmbo" = "ngɑ̌ yá'nthʉ́ mbú ò"
"ngyu" = "ngɑ̌ yú'"
"ngzh" = "ngɑ̌ zhí"
"nh." = "ŋ̄h"
"nhw'n" = "nɑ́hŋwɑ̀'nì"
"nhw'nnzh" = "nɑ́hŋwɑ̀'nǐ nzhǐntē'"
"nhw'nv" = "nɑ́hŋwɑ̀'nǐ vàm"
"nhwn" = "nɑ́hŋwɑ̀'nì"
"nhwnnzh" = "nɑ́hŋwɑ̀'nǐ nzhǐntē'"
"nhwnv" = "nɑ́hŋwɑ̀'nǐ vàm"
"njwnt" = "njwēnɑ̌hntà'"
"nk'c" = "ǹ kɑ̀' cə̄ə̄"
"nk'y'b" = "ǹ kɑ̀' yū' bɑ̄"
"nk'zh" = "ǹ kɑ̀' zhī"
"nk?" = "nǔkɑ́ ?"
"nkb?" = "nǔkɑ́ bɑ́ ɑ̄ ?"
"nkbs?" = "nǔkɑ́ bɑ́ sīē ?"
"nkc" = "ǹ kɑ̀' cə̄ə̄"
"nknd'nd'" = "nǎk ndɑ̀'ndɑ̀'"
"nkpp" = "nǎk pə̀pē'"
"nkw'n$" = "nkwè'nì"
"nkw'nshnk" = "nkwè'nǐ shʉ̀ɑ̄ nkɑ̄ɑ̄"
"nmmnt" = "nǎm mɑ̀ntʉ̄ɑ̄"
"nmnt" = "nǎm mɑ̀ntʉ̄ɑ̄"
"ns'nwnkngktb" = "nù sǐ' nnʉ́ɑ́ wènòk ngʉ́ kǎmthʉ̄ bɑ̄"
"nshnsh'" = "nshùnshʉ̀'"
"nsmnj'b" = "ǹ sī mɑ̀ njū' bɑ̄ "
"nssb" = "nù sī sīē bɑ̄"
"nssi" = "nsìèsì"
"nsw" = "nɑ́hsáhwū"
"nt'" = "nù tɑ̀' !"
"nth a lh mcs" = "nthʉ̄ á lōh mɑ̀ cà'sì"
"nthalhmcs" = "nthʉ̄ á lōh mɑ̀ cà'sì"
"nthlhmc's" = "nthʉ̄ á lōh mɑ̀ cà'sì"
"nthlhmcs" = "nthʉ̄ á lōh mɑ̀ cà'sì"
"ntmbngf" = "ntūmbhìngofāt"
"nzhk m nko a" = "nzhìèkǔ' mɑ̀ nkō à"
"nzhk'mnkoa" = "nzhìèkǔ' mɑ̀ nkō à"
"nzhkmk" = "nzhìèkú' mɑ̀nkō ā"
"nzhkmnkoa" = "nzhìèkǔ' mɑ̀ nkō à"
"nzhndm" = "nzhī ndēn mɑ́"

"nzhwa" = "nzhwīē à"
"nzl?" = "nzɑ̌ léé è ?"
"o s c" = "ǒ sì cə̄ə̄"
"odmbl?" = "ǒ díé mbɑ̄ lāhā ?"
"odmblh?" = "ǒ díé mbɑ̄ lāhā ?"
"ofhmngk?" = "ǒ fhʉ́mɑ̄ngʉ́ kɑ́ ?"
"oghmsp" = "ǒ ghʉ̌ màà sìpè'"
"oho" = "ôhó"
"olmkl?" = "ǒ lén mɑ́ kɑ́ lī?"
"om2" = "ǒ mɑ́"
"omh?" = "ǒ mɑ̀ hɑ̄ ?"
"ommb'" = "ǒ mɑ́ mbâ' !"
"ommba'" = "ǒ mɑ́ mbâ' !"
"ommw?" = "ǒ mɑ́ mên wɑ̄ ?"
"omndmkl?" = "ǒ mɑ̀ndēn mɑ́ kɑ́ lī?"
"omngk?" = "ǒ mɑ̀ngʉ́ kɑ́ ?"
"omngmh?" = "ǒ mɑ̀ngén mɑ̀ hɑ̄ ?"
"omnjnzh?" = "ǒ mɑ̀njīī nzhʉ̀ ʉ́ ?"
"omw?" = "ǒ mɑ́ wɑ̄ ?"
"ongmh?" = "ǒ ngén mɑ̀ hɑ̄ ?"
"ongt$" = "ǒ ngáh tɑ̀'"
"ongt'" = "ǒ ngáh tɑ̀'"
"onnya" = "ò nɛ̀n ɑ̂ yɑ̀?"
"onsmh?" = "ǒ nsī mɑ̀ hɑ̄ ?"
"onspw?" = "ǒ nsī pí wɑ̄ ?"
"opw?" = "ǒ pí wɑ̄ ?"
"osc" = "ǒ sì cə̄ə̄"
"osghf" = "ǒ sì ghʉ́ fà'á"
"osghl" = "ǒ sì ghát lā"
"osghnu" = "ǒ sì ghə́ə́ nù"
"osh" = "ǒ sì hɑ̄"
"oslnu" = "ǒ sì lēn nù"
"ospnk$" = "ǒ sì pūā nkhù"
"ospnkh" = "ǒ sì pūā nkhù"
"p'nshil" = "pɑ́' nshì lɑ́"
"p'w'n" = "pú'ŋwɑ̀'nì"
"pb" = "pīɑ̄ bā"
"pdmbl?" = "pěn díé mbɑ̄ lāhā ?"
"pdmblh?" = "pěn díé mbɑ̄ lāhā ?"
"pdmbnt" = "pɑ̌h díé mbɑ̄ ntèn"
"pghmw" = "pèn ghʉ́ mɑ̀wǎ"
"phpen" = "pɑ́h á pèn"
"pjm" = "pǎtnjàm"
"pk" = "pèn khʉ́ɑ́!"
"pma" = "póómɑ̄"
"pmh?" = "pěn mɑ̀ hɑ̄ ?"
"pml?" = "pěn mɑ̀ lāhā ?"
"pmngk?" = "pěn mɑ̀ngʉ́ kɑ́ ?"
"pmoh" = "pēh mōh!"
"pooma" = "póómɑ̄"
"ppl$" = "pèn pə̄ə̄ lɑ́"
"pplpmo" = "pèn pə̄ə̄ lɑ́ poómɑ̄ ō"
"ps'mb" = "pèn sɑ́' mbə̄ə̄"
"ps'pp" = "pèn sɑ́' pə̀pē'"
"pspp" = "pèn sī pə̀pē'"
"pwk" = "pɑ̄h wūɑ̄kɔ̀ !"
"s'pp" = "sɑ̌' pə̀pē'"
"s0" = "sī nēhē"
"sf'bb" = "sī fà'á bɑ́ bɑ̄"
"sfbb" = "sī fà'á bɑ́ bɑ̄"
"sfsf" = "sì' fà'á, sì' fà'á"
"shck." = "shʉ̀ɑ̀ncāk"
"shnu" = "shʉ̀ɑ́nù !"
"shp$" = "nshʉ̀ɑ̀pʉ̀"
"shpsie" = "nshʉ̀ɑ̀pʉ̀ sīē"
"shwn" = "shwī nā ò"
"ska" = "sōk ā"
"sknk" = "nsāh kɑ́ nnʉ́ɑ́ kɑ́"
"skw'nkw'" = "sìkwè'nkwé'"
"smbb" = "sī mʉ̀ bɑ́ bɑ̄"
"snd'" = "sāhndó'"
"sndndbb" = "sī ndéndēē bɑ́ bɑ̄"
"spp" = "sī pə̀pē'"
"ss" = "sī sīē"
"swe" = "sə̀ə̄wèn"
"swu" = "sə̀ə̄wū"
"sybb" = "sī yʉ̄ɑ̄ bɑ́ bɑ̄"
"t't" = "tɑ̀' tɑ̀'"
"thpo" = "tɑ̌hpō lɑ́"
"tklk" = "tíklìklìklìklìk !"
"tkmb" = "tɑ̀ kēēmbʉ̄ɑ̄"
"tm'l'" = "tɑ̀ mó' līē'"
"tmblb" = "tɑ̀ mbʉ́ɑ́ lɑ̀ bɑ̄"
"tml" = "tɑ̀ mó' līē'"
"tmnd" = "tɑ̀ mêndɑ̀'"
"tmw$" = "tɑ̀ mmíé wǎ'"
"tmw'" = "tɑ̀ mmíé wǎ'"
"tn." = "tēnɑ̄"
"tpl" = "tɑ̌hpō lɑ́"
"twh" = "tɑ̀ wāhà"
"vsm" = "vɑ̀hsìmìè"
"w'n" = "ŋwɑ̀'nì"
"w0" = "wūnèhē"
"wb?" = "wɑ̄ bɑ́ ɑ̄ ?"
"wk" = "wūɑ̄kɔ̀ !"
"wl?" = "wɑ̄ lī ?"
"wndko" = "wò ndǒk ò"
"wnk" = "wènòk"
"wspnkh" = "wěn sì pūā nkhù"
"ww?" = "wò wɑ̄ ?"
"wya?" = "wɑ̄ yà ?"
"wyl?" = "wò yō lɑ́ ō ?"
"wylo?" = "wò yō lɑ́ ō ?"
"wyo" = "wò yō"
"wz" = "wúzɑ̄"
"yb" = "yāā báá !"
"yk'$" = "yáá kù'"
"yk'p" = "yāā kɑ̀' pé'"
"ykp" = "yāā kɑ̀' pé'"
"ykw'f'" = "yáá kwɑ̀' fà'á"
"ykwf" = "yáá kwɑ̀' fà'á"
"ylz" = "yáá lēē zǐ"
"yml" = "yáá mɑ̀ lāhā"
"ymmb$" = "yáá mɑ̀mbé'"
"ymmb'" = "yáá mɑ̀mbé'"
"ymnd'mk?" = "yáá mɑ̀ ndɑ́'sí mɑ́ kɑ́ ?"
"ymndmk?" = "yáá mɑ̀ ndɑ́'sí mɑ́ kɑ́ ?"
"ymnk" = "yáá mɑ̀nnák"
"ymspl" = "yì mɑ̀ Síé pēn lɑ́"
"yndki" = "yʉ̄ɑ̄ ndǒk ì"
"ynzl?" = "yò nzɑ̌ léé è ?"
"yp$" = "yáá pè'"
"ypwb?" = "yēē pí wɑ̄ bɑ́ ɑ̄ ?"
"yshnsh" = "ɑ́ yāā shʉ́ɑ́ nshǔ ó lɑ́"
"ysmmb$" = "yāā sī mɑ̀mbé' bɑ̄"
"ysmmb'b" = "yāā sī mɑ̀mbé' bɑ̄"
"ysmnkb" = "yáá sī mɑ̀nnák bɑ́"
"ytn" = "yā' tēnɑ̄"
"ywb?" = "yǐ wɑ̄ bɑ́ ɑ̄ ?"
"yy$" = "yáá yə̄ə̄"
"yywl" = "yēē yàà wɑ̄ lɑ̄ ē ē !"
"z'mndom" = "zʉ̌' mɑ̀ndóm"


"z'w'n" = "zʉ̌'ŋwɑ̀'nì"
"zh'nsho" = "zhʉ̄ɑ̄' nshù ō"
"zhwngw" = "zhî wèn ngén wūɑ̄"
"zzm$" = "zēn zǎ mɑ́"
"zzmw?" = "zēn zǒ mɑ́ wɑ̄ ?"
