[info]
name = "Ethiopic IM"
description = "Ethiopic Config File"
version = "2024-03-23"
authors = []
website = ""

[core]
buffer_size = 64
auto_capitalize = false
auto_commit = false

[data]
ethiopic = { path = "./code.toml" }

