[code]
"he" = "ሀ"
"hu" = "ሁ"
"hi" = "ሂ"
"ha" = "ሃ"
"hie" = "ሄ"
"h" = "ህ"
"ho" = "ሆ"
"le" = "ለ"
"lu" = "ሉ"
"li" = "ሊ"
"la" = "ላ"
"lie" = "ሌ"
"l" = "ል"
"lo" = "ሎ"
"He" = "ሐ"
"Hu" = "ሑ"
"Hi" = "ሒ"
"Ha" = "ሓ"
"Hie" = "ሔ"
"H" = "ሕ"
"Ho" = "ሖ"
"me" = "መ"
"mu" = "ሙ"
"mi" = "ሚ"
"ma" = "ማ"
"mie" = "ሜ"
"m" = "ም"
"mo" = "ሞ"
"s2e" = "ሠ"
"s2u" = "ሡ"
"s2i" = "ሢ"
"s2a" = "ሣ"
"s2ie" = "ሤ"
"s2" = "ሥ"
"s2o" = "ሦ"
"re" = "ረ"
"ru" = "ሩ"
"ri" = "ሪ"
"ra" = "ራ"
"rie" = "ሬ"
"r" = "ር"
"ro" = "ሮ"
"se" = "ሰ"
"su" = "ሱ"
"si" = "ሲ"
"sa" = "ሳ"
"sie" = "ሴ"
"s" = "ስ"
"so" = "ሶ"
"Se" = "ሸ"
"Su" = "ሹ"
"Si" = "ሺ"
"Sa" = "ሻ"
"Sie" = "ሼ"
"S" = "ሽ"
"So" = "ሾ"
"qe" = "ቀ"
"qu" = "ቁ"
"qi" = "ቂ"
"qa" = "ቃ"
"qie" = "ቄ"
"q" = "ቅ"
"qo" = "ቆ"
"que" = "ቈ"
"qui" = "ቊ"
"qua" = "ቋ"
"quie" = "ቌ"
"qW" = "ቍ"
"Qe" = "ቐ"
"Qu" = "ቑ"
"Qi" = "ቒ"
"Qa" = "ቓ"
"Qie" = "ቔ"
"Q" = "ቕ"
"Qo" = "ቖ"
"Que" = "ቘ"
"Qui" = "ቚ"
"Qua" = "ቛ"
"Quie" = "ቜ"
"QW" = "ቝ"
"be" = "በ"
"bu" = "ቡ"
"bi" = "ቢ"
"ba" = "ባ"
"bie" = "ቤ"
"b" = "ብ"
"bo" = "ቦ"
"ve" = "ቨ"
"vu" = "ቩ"
"vi" = "ቪ"
"va" = "ቫ"
"vie" = "ቬ"
"v" = "ቭ"
"vo" = "ቮ"
"te" = "ተ"
"tu" = "ቱ"
"ti" = "ቲ"
"ta" = "ታ"
"tie" = "ቴ"
"t" = "ት"
"to" = "ቶ"
"ce" = "ቸ"
"cu" = "ቹ"
"ci" = "ቺ"
"ca" = "ቻ"
"cie" = "ቼ"
"c" = "ች"
"co" = "ቾ"
"h2e" = "ኀ"
"h2u" = "ኁ"
"h2i" = "ኂ"
"h2a" = "ኃ"
"h2ie" = "ኄ"
"h2" = "ኅ"
"h2o" = "ኆ"
"hue" = "ኈ"
"hui" = "ኊ"
"hua" = "ኋ"
"huie" = "ኌ"
"hW" = "ኍ"
"ne" = "ነ"
"nu" = "ኑ"
"ni" = "ኒ"
"na" = "ና"
"nie" = "ኔ"
"n" = "ን"
"no" = "ኖ"
"Ne" = "ኘ"
"Nu" = "ኙ"
"Ni" = "ኚ"
"Na" = "ኛ"
"Nie" = "ኜ"
"N" = "ኝ"
"No" = "ኞ"
"e" = "አ"
"u" = "ኡ"
"i" = "ኢ"
"a" = "ኣ"
"ie" = "ኤ"
"A" = "እ"
"o" = "ኦ"
"ke" = "ከ"
"ku" = "ኩ"
"ki" = "ኪ"
"ka" = "ካ"
"kie" = "ኬ"
"k" = "ክ"
"ko" = "ኮ"
"kue" = "ኰ"
"kui" = "ኲ"
"kua" = "ኳ"
"kuie" = "ኴ"
"kW" = "ኵ"
"Ke" = "ኸ"
"Ku" = "ኹ"
"Ki" = "ኺ"
"Ka" = "ኻ"
"Kie" = "ኼ"
"K" = "ኽ"
"Ko" = "ኾ"
"Kue" = "ዀ"
"Kui" = "ዂ"
"Kua" = "ዃ"
"Kuie" = "ዄ"
"KW" = "ዅ"
"we" = "ወ"
"wu" = "ዉ"
"wi" = "ዊ"
"wa" = "ዋ"
"wie" = "ዌ"
"w" = "ው"
"wo" = "ዎ"
"Oe" = "ዐ"
"Ou" = "ዑ"
"Oi" = "ዒ"
"Oa" = "ዓ"
"Oie" = "ዔ"
"O" = "ዕ"
"Oo" = "ዖ"
"ze" = "ዘ"
"zu" = "ዙ"
"zi" = "ዚ"
"za" = "ዛ"
"zie" = "ዜ"
"z" = "ዝ"
"zo" = "ዞ"
"Ze" = "ዠ"
"Zu" = "ዡ"
"Zi" = "ዢ"
"Za" = "ዣ"
"Zie" = "ዤ"
"Z" = "ዥ"
"Zo" = "ዦ"
"ye" = "የ"
"yu" = "ዩ"
"yi" = "ዪ"
"ya" = "ያ"
"yie" = "ዬ"
"y" = "ይ"
"yo" = "ዮ"
"de" = "ደ"
"du" = "ዱ"
"di" = "ዲ"
"da" = "ዳ"
"die" = "ዴ"
"d" = "ድ"
"do" = "ዶ"
"je" = "ጀ"
"ju" = "ጁ"
"ji" = "ጂ"
"ja" = "ጃ"
"jie" = "ጄ"
"j" = "ጅ"
"jo" = "ጆ"
"ge" = "ገ"
"gu" = "ጉ"
"gi" = "ጊ"
"ga" = "ጋ"
"gie" = "ጌ"
"g" = "ግ"
"go" = "ጎ"
"gue" = "ጐ"
"gui" = "ጒ"
"gua" = "ጓ"
"guie" = "ጔ"
"gW" = "ጕ"
"Te" = "ጠ"
"Tu" = "ጡ"
"Ti" = "ጢ"
"Ta" = "ጣ"
"Tie" = "ጤ"
"T" = "ጥ"
"To" = "ጦ"
"Ce" = "ጨ"
"Cu" = "ጩ"
"Ci" = "ጪ"
"Ca" = "ጫ"
"Cie" = "ጬ"
"C" = "ጭ"
"Co" = "ጮ"
"Pe" = "ጰ"
"Pu" = "ጱ"
"Pi" = "ጲ"
"Pa" = "ጳ"
"Pie" = "ጴ"
"P" = "ጵ"
"Po" = "ጶ"
"xe" = "ጸ"
"xu" = "ጹ"
"xi" = "ጺ"
"xa" = "ጻ"
"xie" = "ጼ"
"x" = "ጽ"
"xo" = "ጾ"
"x2e" = "ፀ"
"x2u" = "ፁ"
"x2i" = "ፂ"
"x2a" = "ፃ"
"x2ie" = "ፄ"
"x2" = "ፅ"
"x2o" = "ፆ"
"fe" = "ፈ"
"fu" = "ፉ"
"fi" = "ፊ"
"fa" = "ፋ"
"fie" = "ፌ"
"f" = "ፍ"
"fo" = "ፎ"
"pe" = "ፐ"
"pu" = "ፑ"
"pi" = "ፒ"
"pa" = "ፓ"
"pie" = "ፔ"
"p" = "ፕ"
"po" = "ፖ"
"." = "።"
";" = "፡"
"," = "፣"
":" = "፥"
"::" = "፤"
";-" = "፦"
".." = "."
"1^" = "፩"
"2^" = "፪"
"3^" = "፫"
"4^" = "፬"
"5^" = "፭"
"6^" = "፮"
"7^" = "፯"
"8^" = "፰"
"9^" = "፱"
"1^0" = "፲"
"2^0" = "፳"
"3^0" = "፴"
"4^0" = "፵"
"5^0" = "፶"
"6^0" = "፷"
"7^0" = "፸"
"8^0" = "፹"
"9^0" = "፺"
"1^00" = "፻"
"1^000" = "፼"
"Ge" = "ጘ"
"Gu" = "ጙ"
"Gi" = "ጚ"
"Ga" = "ጛ"
"Gie" = "ጜ"
"G" = "ጝ"
"Go" = "ጞ"
"Gue" = "ⶓ"
"Gui" = "ⶔ"
"Gua" = "ጟ"
"Guie" = "ⶕ"
"GW" = "ⶖ"
"hoa" = "ሇ"
"lua" = "ሏ"
"Hua" = "ሗ"
"mua" = "ሟ"
"s2ua" = "ሧ"
"rua" = "ሯ"
"sua" = "ሷ"
"Sua" = "ሿ"
"qoa" = "ቇ"
"bua" = "ቧ"
"vua" = "ቯ"
"tua" = "ቷ"
"cua" = "ቿ"
"nua" = "ኗ"
"Nua" = "ኟ"
"ua" = "ኧ"
"koa" = "ኯ"
"woa" = "ዏ"
"zua" = "ዟ"
"Zua" = "ዧ"
"yoa" = "ዯ"
"dua" = "ዷ"
"jua" = "ጇ"
"goa" = "ጏ"
"Tua" = "ጧ"
"Cua" = "ጯ"
"Pua" = "ጷ"
"xua" = "ጿ"
"x2ua" = "ፇ"
"fua" = "ፏ"
"pua" = "ፗ"
"d2e" = "ዸ"
"d2u" = "ዹ"
"d2i" = "ዺ"
"d2a" = "ዻ"
"d2ie" = "ዼ"
"d2" = "ዽ"
"d2o" = "ዾ"
"d2ua" = "ዿ"
"ri2" = "ፘ"
"mi2" = "ፙ"
"fi2" = "ፚ"
"??" = "፧"
"..." = "፨"
"...." = "፠"
