[info]
description = "Letters in bamun script"
source = "https://www.unicode.org/charts/PDF/UA6A0.pdf"
version = "2024-03-23"

[data]
"a" = "ꚠ"
"ka" = "ꚡ"
"u" = "ꚢ"
"ku" = "ꚣ"
"ee" = "ꚤ"
"ree" = "ꚥ"
"tae" = "ꚦ"
"o" = "ꚧ"
"nyi" = "ꚨ"
"i" = "ꚩ"
"la" = "ꚪ"
"pa" = "ꚫ"
"rii" = "ꚬ"
"riee" = "ꚭ"
"leeee" = "ꚮ"
"meeee" = "ꚯ"
"taa" = "ꚰ"
"ndaa" = "ꚱ"
"njaem" = "ꚲ"
"m" = "ꚳ"
"suu" = "ꚴ"
"mu" = "ꚵ"
"shii" = "ꚶ"
"si" = "ꚷ"
"sheux" = "ꚸ"
"seux" = "ꚹ"
"kyee" = "ꚺ"
"ket" = "ꚻ"
"nuae" = "ꚼ"
"nu" = "ꚽ"
"njuae" = "ꚾ"
"yoq" = "ꚿ"
"shu" = "ꛀ"
"yuq" = "ꛁ"
"ya" = "ꛂ"
"nsha" = "ꛃ"
"keux" = "ꛄ"
"peux" = "ꛅ"
"njee" = "ꛆ"
"ntee" = "ꛇ"
"pue" = "ꛈ"
"wue" = "ꛉ"
"pee" = "ꛊ"
"fee" = "ꛋ"
"ru" = "ꛌ"
"lu" = "ꛍ"
"mi" = "ꛎ"
"ni" = "ꛏ"
"reux" = "ꛐ"
"rae" = "ꛑ"
"ken" = "ꛒ"
"ngkwaen" = "ꛓ"
"ngga" = "ꛔ"
"nga" = "ꛕ"
"sho" = "ꛖ"
"puae" = "ꛗ"
"fu" = "ꛘ"
"fom" = "ꛙ"
"wa" = "ꛚ"
"na" = "ꛛ"
"li" = "ꛜ"
"pi" = "ꛝ"
"loq" = "ꛞ"
"ko" = "ꛟ"
"mben" = "ꛠ"
"ren" = "ꛡ"
"men" = "ꛢ"
"ma" = "ꛣ"
"ti" = "ꛤ"
"ki" = "ꛥ"
"mo" = "ꛦ"

