[info]
description = "Punctuations in bamun scripts"
source = "https://www.unicode.org/charts/PDF/UA6A0.pdf"
version = "2024-03-23"

[data]
"koqndon" = "$꛰"
"tukwentis" = "$꛱"
"njaemli" = "꛲"
"." = "꛳"
":" = "꛴"
"," = "꛵"
";" = "꛶"
"?" = "꛷"
