[info]
name		=	"nufi"
description = 	"Nufi Config File"
authors		=	["Resulam <contact@resulam.com>"]
website		=	"https://resulam.com"
version		=	"2023-10-02"

[translation]
sms = { path = "./nufi_sms.toml" }

[translator]
date = "./scripts/datetime/date.rhai"
numerals = "./scripts/numerals.rhai"

[data]
clafrica = { path = "../clafrica/clafrica.toml" }
